### ISSUE TITLE
Chests from campaign missions aren’t included in local chests table, causing hard errors.

### ISSUE THREAD

**Issue by Zegnat** [anoutsider/advanced-logistics-system#4] opened 2015-10-20 17:05 UTC
My guess is that chests from campaign missions aren’t included in the local chests table. This means trying to pick them up throws an error and then quits the game. Noticed this when I was playing the third level of the <b>base/First steps</b> campaign.

```
Notice
Error while running the event handler: __advanced-logistics-system__/control.lua:427: attempt to index local 'chests' (a nil value)
```

Would it be possible to pre-populate the local table with chests that are already on the level when it loads?

![Screenshot: displaying the notice.](https://cloud.githubusercontent.com/assets/490579/10614939/439033ec-775d-11e5-9671-675b04832922.png)

**Comment by Danielv123** [comment] 2015-11-15 21:56
Alternative possible solution:
if this.chest exists {
  this.removeFromTable()
  this.destroy()
} else {
  this.destroy
}

But thats just my five cents. Long time since I have done any lua.

**Comment by anoutsider** [comment] 2015-11-15 22:12
Sorry i completely missed this issue, to me it doesn't seem to be an issue with missing chest types, the global data itself seems to be missing, could be an issue with the game not running the init event in the campaign.

is the mod itself working? because judging by the error it shouldn't be showing anything at all, anyway i will have to run some test on the campaign myself and will let you know if i come up with a fix.

**Comment by Zegnat** [comment] 2015-11-22 16:26
> is the mod itself working?

I haven’t been using it currently, but everything seemed to work perfectly back then. It is just pre-placed chests that seemed to fail.

**Comment by judos** [comment] 2016-02-03 19:53
Hi anoutsider,

I found also a crash which probably is the same issue as this one. As this issue is not tagged oon which version it occured i'm not totally sure.
This happened while shooting an enemy chest:
`Error while running the event handler: __advanced-logistics-system__/control.lua:447: attempt to index local 'chests' (a nil value)`
The problem is that the array global.normalChests[force] is only initialized when a player is created. However this is not the case for several other cases e.g. tutorial, spawning in creatively etc.
You can fix this easily by adding checks like so:

```
local chests = global.normalChests[force]
if chests then
...
end
```

**Comment by anoutsider** [comment] 2016-02-29 18:45
Hi judos,

I finally got to test the mod in scenario/campaign modes, Version 0.2.11 should fix these crash issues.. ideally i'd have worked on including pre-populated chests but they are not assigned to the player force, so it'd require special coding and i felt it wasn't really required after playing a bit with the scenarios.

Please let me know if you guys are still having issues with this, Thanks and sorry for the delays.

**Comment by anoutsider** [comment] 2016-04-15 07:29
Since there has been no updates on this, i'm assuming it's fixed.

Closing.

**Closed as completed by anoutsider** 2016-04-15 07:29 UTC
